/**
 * Real Organics - Product Catalog & Traceability Dataset
 * Origin: Pendurthi & Surrounding Agro-Clusters, Visakhapatnam, Andhra Pradesh
 */

const PRODUCTS = [
  {
    id: "oil-groundnut-coldpressed",
    name: "Wood-Churned Groundnut Oil (వేరుశెనగ నూనె)",
    teluguName: "గానుగ వేరుశెనగ నూనె",
    category: "oils",
    categoryLabel: "Cold-Pressed Gaani Oils",
    price: 340,
    unit: "1 Litre Glass Bottle",
    rating: 4.9,
    reviews: 142,
    badge: "100% Vaagai Wood Churned",
    origin: "Pendurthi Agro-Cluster, Visakhapatnam",
    coordinates: "17.8312° N, 83.2014° E",
    farmer: "Appala Naidu & Community Co-op",
    harvestDate: "October 2026",
    batchCode: "VIZ-PND-OIL-428",
    modelType: "bottle_oil",
    modelColor: 0xe6a817,
    purityStats: {
      pesticides: "0.00% (Not Detected)",
      coldPressTemp: "31.4°C (Raw Cold Extraction)",
      chemicals: "Zero Preservatives / Unrefined",
      polyphenols: "High Antioxidant Retention"
    },
    shortDesc: "Traditional bull-driven wood gaani extracted at low friction temperature to preserve vitamin E and aroma.",
    fullDesc: "Crushed in native Vaagai (Lebbeck) wooden mortar and pestle at temperatures under 32°C. Never bleached, never de-odorized, and bottled unfiltered in dark UV-resistant glass bottles in our Pendurthi processing facility.",
    healthBenefits: ["Zero trans-fat", "Rich in monounsaturated fats (MUFA)", "Natural nutty aroma enhances Andhra curries & dosas"],
    inStock: true,
    featured: true
  },
  {
    id: "honey-araku-wild",
    name: "Araku Valley Raw Rock-Bee Honey (అడవి తేనె)",
    teluguName: "అరకు కొండల సహజ అడవి తేనె",
    category: "honey",
    categoryLabel: "Raw Forest Honey & Jaggery",
    price: 480,
    unit: "500g Hex Jar",
    rating: 5.0,
    reviews: 218,
    badge: "Wild Tribal Harvested",
    origin: "Ananthagiri - Araku Eastern Ghats",
    coordinates: "18.2831° N, 82.9739° E",
    farmer: "Girijan Tribal Honey Gatherers",
    harvestDate: "September 2026",
    batchCode: "ARK-HNY-WLD-890",
    modelType: "honey_jar",
    modelColor: 0xd97706,
    purityStats: {
      pesticides: "0.00% Pure Wild Flora",
      coldPressTemp: "Unheated / Raw (Below 30°C)",
      chemicals: "Zero Added Sugar Syrup",
      polyphenols: "Enzyme Rich & Active Pollen"
    },
    shortDesc: "Unpasteurized, coarse-filtered multifloral honey gathered from cliff rock bees in high altitude misty forests.",
    fullDesc: "Directly brought to our Pendurthi store through direct fair-trade with Eastern Ghats tribal cooperatives. Retains living enzymes, antimicrobial pollen, and subtle notes of wild forest blossoms and medicinal flora.",
    healthBenefits: ["Natural immunity booster", "Soothes cough & throat irritation", "Natural enzyme digestion aid"],
    inStock: true,
    featured: true
  },
  {
    id: "millet-foxtail-korralu",
    name: "Unpolished Foxtail Millet (కొర్రలు)",
    teluguName: "దేశవాళీ కొర్రలు (పాలిష్ లేనివి)",
    category: "millets",
    categoryLabel: "Heritage Millets & Grains",
    price: 135,
    unit: "1 kg Sealed Eco-Pack",
    rating: 4.8,
    reviews: 94,
    badge: "Native Rain-Fed Heirloom",
    origin: "Sabbavaram - Pendurthi Drylands",
    coordinates: "17.8010° N, 83.1322° E",
    farmer: "K. Satyanarayana & Family",
    harvestDate: "August 2026",
    batchCode: "VIZ-MLT-FOX-711",
    modelType: "clay_pot_millets",
    modelColor: 0xdeb887,
    purityStats: {
      pesticides: "0.00% Certified Organic Soil",
      coldPressTemp: "Dehusked with Rubber Sheller",
      chemicals: "100% Unbleached Bran Retained",
      polyphenols: "Low GI < 50 / High Dietary Fiber"
    },
    shortDesc: "Ancient miracle grain rich in fiber and iron, grown in chemical-free red loamy soil with natural monsoon rainwater.",
    fullDesc: "Naturally drought-resilient heirloom variety. Traditionally dehusked without buffing away the mineral-rich bran layer. Ideal for substituting white rice in daily meals, khichdi, idli batter, and porridge.",
    healthBenefits: ["Low glycemic index (diabetic friendly)", "Supports sustained energy release", "High protein and magnesium"],
    inStock: true,
    featured: true
  },
  {
    id: "turmeric-lakadong-highcurcumin",
    name: "Hill-Grown Lakadong Turmeric (పసుపు)",
    teluguName: "సేంద్రీయ కొండ పసుపు (7.8% కర్క్యుమిన్)",
    category: "spices",
    categoryLabel: "Stone-Ground Hill Spices",
    price: 180,
    unit: "250g Glass Jar",
    rating: 4.9,
    reviews: 165,
    badge: "7.8% High Curcumin Certified",
    origin: "Paderu High Hills, Visakhapatnam Dist",
    coordinates: "18.0833° N, 82.6667° E",
    farmer: "Chitti Babu & Organic Guild",
    harvestDate: "July 2026",
    batchCode: "PAD-TRM-CUR-309",
    modelType: "spice_mortar",
    modelColor: 0xf59e0b,
    purityStats: {
      pesticides: "0.00% Heavy Metal Free (No Lead)",
      coldPressTemp: "Slow Stone Mill Pulverized",
      chemicals: "Zero Artificial Colorants (Metanil Free)",
      polyphenols: "7.82% Curcumin Lab Verified"
    },
    shortDesc: "Deep golden organic turmeric with nearly triple the curcumin content of commercial grocery powders.",
    fullDesc: "Grown in virgin mountain soils enriched with forest leaf mould and cow-dung jeevamrutham. Sun-cured on natural reed mats and pulverized at low RPM on stone mills in Pendurthi to prevent heat loss of essential volatile oils.",
    healthBenefits: ["Potent anti-inflammatory", "High antioxidant cellular protection", "Promotes joint comfort and gut health"],
    inStock: true,
    featured: true
  },
  {
    id: "oil-sesame-coldpressed",
    name: "Cold-Pressed Sesame Oil (నువ్వుల నూనె)",
    teluguName: "గానుగ నల్ల నువ్వుల నూనె",
    category: "oils",
    categoryLabel: "Cold-Pressed Gaani Oils",
    price: 380,
    unit: "1 Litre Glass Bottle",
    rating: 4.9,
    reviews: 87,
    badge: "Wood Pressed with Palm Jaggery",
    origin: "Chodavaram Organic Cluster",
    coordinates: "17.8300° N, 82.9300° E",
    farmer: "Sanyasi Rao Farmers Group",
    harvestDate: "September 2026",
    batchCode: "VIZ-PND-SES-512",
    modelType: "bottle_oil",
    modelColor: 0x92400e,
    purityStats: {
      pesticides: "0.00% Lab Screened",
      coldPressTemp: "30.8°C Traditional Wood Churn",
      chemicals: "Zero Hexane Extraction",
      polyphenols: "Rich in Sesamol & Vitamin E"
    },
    shortDesc: "Crafted using black sesame seeds and tiny touch of organic palm jaggery in wooden gaani press.",
    fullDesc: "Celebrated in traditional Andhra ayurveda as the supreme oil for internal lubrication and authentic pickles (avakkai). Extracted without thermal or chemical refinement.",
    healthBenefits: ["Balances Vata dosha", "Rich in calcium and healthy plant lignans", "Superb smoke stability for authentic cooking"],
    inStock: true,
    featured: false
  },
  {
    id: "jaggery-palm-taatibellam",
    name: "Pure Palm Jaggery Blocks (తాటి బెల్లం)",
    teluguName: "సహజ తాటి బెల్లం",
    category: "honey",
    categoryLabel: "Raw Forest Honey & Jaggery",
    price: 260,
    unit: "500g Leaf Wrapped",
    rating: 4.8,
    reviews: 112,
    badge: "Zero Sulphur / Unbleached",
    origin: "Bhimili Coastal Palm Groves",
    coordinates: "17.8894° N, 83.4542° E",
    farmer: "Ramanamma Coastal Harvesters",
    harvestDate: "August 2026",
    batchCode: "BHM-PLM-JAG-104",
    modelType: "honey_jar",
    modelColor: 0x78350f,
    purityStats: {
      pesticides: "0.00% Chemical Residues",
      coldPressTemp: "Clarified with Wild Okra Extract",
      chemicals: "Zero Sulphites / Zero Sodium Hydrosulphite",
      polyphenols: "High Iron & Mineral Ash Content"
    },
    shortDesc: "Rich, dark, caramel-tasting natural sweetener hand-boiled from fresh palmyra palm sap.",
    fullDesc: "Crafted using generational artisanal boiling methods without industrial chemical clarifiers. Low glycemic index compared to white sugar, brimming with potassium, magnesium, and bioavailable iron.",
    healthBenefits: ["Prevents post-meal sugar spikes", "Naturally boosts hemoglobin", "Traditional remedy for throat soothing"],
    inStock: true,
    featured: false
  },
  {
    id: "produce-heirloom-country-mango",
    name: "Organic Suvarnarekha Mangoes (బేగంపల్లి & సువర్ణరేఖ)",
    teluguName: "తోట నుండి కోసిన సహజ మామిడి పండ్లు",
    category: "produce",
    categoryLabel: "Dawn-Harvested Fresh Produce",
    price: 320,
    unit: "3 kg Fresh Farm Crate",
    rating: 5.0,
    reviews: 79,
    badge: "Tree-Ripened (Zero Carbide)",
    origin: "Kothavalasa Hill Orchards",
    coordinates: "17.9167° N, 83.2167° E",
    farmer: "Surya Narayana Agro Farm",
    harvestDate: "Dawn Picked Today",
    batchCode: "KTH-MGO-ORG-019",
    modelType: "heirloom_fruit",
    modelColor: 0xf59e0b,
    purityStats: {
      pesticides: "0.00% Zero Synthetic Spraying",
      coldPressTemp: "Naturally Hay-Ripened",
      chemicals: "100% Free of Calcium Carbide / Ethylene dip",
      polyphenols: "High Natural Vitamin A & C"
    },
    shortDesc: "Luscious, fragrant sun-ripened heritage mangoes harvested straight into padded straw crates at first light.",
    fullDesc: "Grown without systematic fungicides or synthetic ripening gases. Allowed to ripen slowly on rice straw bedding at our Pendurthi ambient store cellar, preserving heavenly sweetness and natural enzymes.",
    healthBenefits: ["Rich in digestive enzymes", "Natural carotenes for eye vitality", "Authentic native fragrance"],
    inStock: true,
    featured: true
  },
  {
    id: "rice-black-kavuni",
    name: "Heirloom Karuppu Kavuni Black Rice (నల్ల బియ్యం)",
    teluguName: "పురాతన ఆరోగ్య నల్ల బియ్యం",
    category: "millets",
    categoryLabel: "Heritage Millets & Grains",
    price: 210,
    unit: "1 kg Cloth Bag",
    rating: 4.9,
    reviews: 63,
    badge: "Anthocyanin-Rich Supergrain",
    origin: "Anandapuram Natural Paddies",
    coordinates: "17.8920° N, 83.3710° E",
    farmer: "Eshwar Rao Permaculture",
    harvestDate: "August 2026",
    batchCode: "VIZ-RCE-BLK-224",
    modelType: "clay_pot_millets",
    modelColor: 0x312e81,
    purityStats: {
      pesticides: "0.00% Zero Chemical Fertilizers",
      coldPressTemp: "Stone De-Husked",
      chemicals: "Zero Paraffin Coating",
      polyphenols: "Highest Anthocyanin Content"
    },
    shortDesc: "Ancient royal heirloom rice with a nutty aroma and intense purple-black bran layer packed with antioxidants.",
    fullDesc: "Historically revered as the elixir of longevity. Cultivated with traditional organic mulching and neem oil decoctions. Incredible for porridge, herbal rice puddings, and fiber-dense lunch bowls.",
    healthBenefits: ["High anthocyanin levels matching blueberries", "Cardiovascular wellness support", "Naturally gluten-free grain"],
    inStock: true,
    featured: false
  },
  {
    id: "ghee-a2-bilona",
    name: "Desi Cow A2 Cultured Bilona Ghee (ఆవు నెయ్యి)",
    teluguName: "గానుగ మట్టి పాత్రలో కాచిన దేశీ ఆవు నెయ్యి",
    category: "oils",
    categoryLabel: "Cold-Pressed Gaani Oils",
    price: 890,
    unit: "500 ml Glass Jar",
    rating: 5.0,
    reviews: 189,
    badge: "Curd Cultured (Bilona Method)",
    origin: "Sabbavaram Natural Goshala",
    coordinates: "17.7850° N, 83.1250° E",
    farmer: "Gopala Krishna Trust",
    harvestDate: "Weekly Churned",
    batchCode: "SAB-GHE-BIL-619",
    modelType: "honey_jar",
    modelColor: 0xfacc15,
    purityStats: {
      pesticides: "0.00% Zero Hormone / Antibiotic Free",
      coldPressTemp: "Slow Fire Earthen Simmering",
      chemicals: "Zero Color Added / 100% Native Ongole Cows",
      polyphenols: "Rich in Butyric Acid & CLA"
    },
    shortDesc: "Traditional Vedic ghee hand-churned from whole A2 cultured yogurt using bidirectional wooden churn.",
    fullDesc: "Crafted exclusively from grass-fed indigenous Ongole and Punganur cows roaming local green pasturelands. Never made from industrial cream; slow simmered over dried dung-cake wood fire in bronze containers.",
    healthBenefits: ["Nourishes brain cells and ojas", "Strengthens gut lining with butyrate", "Aids fat-soluble vitamin absorption"],
    inStock: true,
    featured: true
  },
  {
    id: "skincare-kumkumadi-tailam",
    name: "Kashmir Saffron Kumkumadi Tailam (కుంకుమాది తైలం)",
    teluguName: "సహజ మూలికా ముఖ తైలం",
    category: "personal-care",
    categoryLabel: "Cold-Process Botanical Body Care",
    price: 650,
    unit: "30 ml Amber Dropper",
    rating: 4.9,
    reviews: 78,
    badge: "16 Ayurvedic Botanicals",
    origin: "Real Organics Botanical Lab, Pendurthi",
    coordinates: "17.8288° N, 83.2034° E",
    farmer: "In-house Ayurvedic Vaidya Formulation",
    harvestDate: "Fresh Small Batch",
    batchCode: "PND-SKN-KUM-102",
    modelType: "botanical_tin",
    modelColor: 0xd97706,
    purityStats: {
      pesticides: "0.00% Lab Certified",
      coldPressTemp: "14-Day Herb Infusion in Sesame Oil",
      chemicals: "Zero Mineral Oils / Zero Parabens",
      polyphenols: "Pure Mogra Saffron Stigmas"
    },
    shortDesc: "Ancient radiance elixir hand-brewed with pure hill saffron, Indian sandalwood, vetiver, and lotus stamens.",
    fullDesc: "Formulated according to Charaka Samhita guidelines at our Pendurthi dispensary. Gently brightens skin tone, reduces hyperpigmentation, and imparts an organic golden glow without artificial silicones.",
    healthBenefits: ["Deep cellular skin regeneration", "Evens out skin texture naturally", "Zero synthetic fragrance"],
    inStock: true,
    featured: false
  },
  {
    id: "produce-raw-turmeric-ginger",
    name: "Hill Ginger & Raw Turmeric Roots (అల్లం & పచ్చి పసుపు)",
    teluguName: "కొండ అల్లం మరియు తాజా పచ్చి పసుపు",
    category: "produce",
    categoryLabel: "Dawn-Harvested Fresh Produce",
    price: 140,
    unit: "1 kg Jute Pouch",
    rating: 4.8,
    reviews: 52,
    badge: "Unwashed Living Soil Roots",
    origin: "Araku Valley Foothills",
    coordinates: "18.1500° N, 83.0200° E",
    farmer: "Chandraiah Tribal Cooperative",
    harvestDate: "Dug This Morning",
    batchCode: "ARK-RHO-ROOT-045",
    modelType: "clay_pot_millets",
    modelColor: 0xd97706,
    purityStats: {
      pesticides: "0.00% Wild Forest Loam Soil",
      coldPressTemp: "Naturally Dried in Shade",
      chemicals: "Zero Chemical Bleach / Acid Wash",
      polyphenols: "Volatile Gingerol & Curcuminoids"
    },
    shortDesc: "Fiery, aromatic fresh roots dug by hand from rich hill soil, unbleached and bursting with life-affirming juices.",
    fullDesc: "Unlike commercial supermarket ginger that is washed with acid to appear pale and shiny, our roots retain their natural soil coat and essential aromatics for herbal teas, fresh chutneys, and traditional kashayams.",
    healthBenefits: ["Boosts digestive fire (Agni)", "Natural decongestant and anti-microbial", "Potent cellular revitalization"],
    inStock: true,
    featured: false
  },
  {
    id: "spices-guntur-sannam-chilli",
    name: "Sun-Dried Guntur Sannam Chillies (ఎండు మిర్చి)",
    teluguName: "ఎండబెట్టిన దేశీ గుంటూరు ఎండుమిరపకాయలు",
    category: "spices",
    categoryLabel: "Stone-Ground Hill Spices",
    price: 160,
    unit: "500g Burlap Pouch",
    rating: 4.9,
    reviews: 133,
    badge: "Zero Sulphur / Sun Cured",
    origin: "Guntur - Krishna River Basin",
    coordinates: "16.3067° N, 80.4365° E",
    farmer: "Koteswara Rao Natural Farms",
    harvestDate: "August 2026",
    batchCode: "GNT-CHL-SNM-781",
    modelType: "spice_mortar",
    modelColor: 0xdc2626,
    purityStats: {
      pesticides: "0.00% Zero Synthetic Organophosphates",
      coldPressTemp: "Naturally Sun Dried on Terracotta",
      chemicals: "Zero Sudan Red Dyes / Unadulterated",
      polyphenols: "High Capsaicin & Natural Deep Red"
    },
    shortDesc: "Celebrated indigenous Andhra chilli hand-picked at peak crimson maturity and slow sun-cured.",
    fullDesc: "Deep fiery warmth with a complex smoky undertone. Never fumigated with sulphur or dyed with toxic synthetic colourants. Gives pure natural colour and traditional kick to Andhra curries and podis.",
    healthBenefits: ["Stimulates healthy metabolic rate", "High natural beta-carotene", "Rich in vitamin C"],
    inStock: true,
    featured: false
  }
];

const FARM_JOURNEY_STAGES = [
  {
    step: 1,
    id: "stage-farm",
    title: "1. THE LIVING FARM",
    telugu: "జీవధార నేల & పొలం",
    subtitle: "Pristine Soil of Eastern Ghats Foothills",
    location: "Pendurthi & Ananthagiri Foothills, Visakhapatnam",
    quote: "Healthy crops begin with living soil, never chemical fertilizers.",
    image: "assets/natural_farm_hero.jpg",
    details: [
      { label: "Soil Microbiome", value: "Enriched with Cow Dung Jeevamrutham & Panchagavya" },
      { label: "Water Source", value: "Fresh Himalayan-age subterranean springs & rainwater collection" },
      { label: "Chemicals Used", value: "0.00% Synthetics, Zero Glyphosate, 100% Certified Organic" },
      { label: "Active Farms", value: "42 Family-Run Natural Farms in Pendurthi Agro-Belt" }
    ],
    interactivePrompt: "Explore the soil composition & morning climate that nurtures our harvest."
  },
  {
    step: 2,
    id: "stage-harvest",
    title: "2. THE SACRED HARVEST",
    telugu: "చేతికోత & రైతు అనుబంధం",
    subtitle: "Hand-Picked at First Light by Generational Farmers",
    location: "Sabbavaram, Kothavalasa & Pendurthi Fields",
    quote: "Picked when nature decrees ripeness — never prematurely ripened in chemical chambers.",
    image: "assets/natural_harvest.jpg",
    secondaryImage: "assets/natural_farmer_portrait.jpg",
    details: [
      { label: "Harvest Ritual", value: "Manual harvesting into natural bamboo baskets at 5:30 AM" },
      { label: "Farmer Fairness", value: "Direct fair price paid within 24 hours (Zero middle-men)" },
      { label: "Produce Purity", value: "Zero wax coatings, zero carbide, 100% unbleached" },
      { label: "Traceability", value: "Every basket tagged with farmer name & GPS coordinates" }
    ],
    interactivePrompt: "Meet our farming families and see how ancestral harvest techniques protect produce."
  },
  {
    step: 3,
    id: "stage-quality",
    title: "3. PURITY & STONE EXTRACTION",
    telugu: "గానుగ నూనె & నాణ్యత తనిఖీ",
    subtitle: "Slow Cold-Pressing & Batch Chromatography Testing",
    location: "Real Organics Artisanal Processing Unit, Pendurthi",
    quote: "Low friction, slow RPM, zero chemicals. Purity you can taste and smell.",
    image: "assets/natural_products.jpg",
    details: [
      { label: "Oil Pressing", value: "Vaagai (Lebbeck) wood churn below 32°C (Lakdi Ghani)" },
      { label: "Honey Purity", value: "Unpasteurized, coarse-filtered, retaining living enzymes" },
      { label: "Lab Verification", value: "Every batch tested by NABL accredited food testing lab" },
      { label: "Public Traceability", value: "Scan batch code on every bottle to view lab gas-chromatography" }
    ],
    interactivePrompt: "Inspect real-time batch lab reports and watch how cold-press gaani extraction works."
  },
  {
    step: 4,
    id: "stage-store",
    title: "4. THE PENDURTHI STORE",
    telugu: "పెందుర్తి నిలయం - మన సేంద్రీయ అంగడి",
    subtitle: "A Botanical Sanctuary in the Heart of Pendurthi",
    location: "Main Road, Near Pendurthi Junction, Visakhapatnam - 531173",
    quote: "A welcoming earth-toned sanctuary filled with the fragrance of pure oils and fresh harvest.",
    image: "assets/pendurthi_store.jpg",
    details: [
      { label: "Store Timings", value: "Monday to Sunday: 6:30 AM – 9:30 PM" },
      { label: "Zero-Waste Refill", value: "Bring your own containers for oils & grains and get 5% rebate" },
      { label: "Sunday Farmer Meet", value: "Every Sunday 8 AM: Direct conversation with our partner farmers" },
      { label: "Contact & WhatsApp", value: "+91 891 274 5890 / +91 94901 88421" }
    ],
    interactivePrompt: "Visit our physical store or arrange instant local pickup right here in Pendurthi."
  },
  {
    step: 5,
    id: "stage-home",
    title: "5. TO YOUR FAMILY HOME",
    telugu: "మీ ఇంట ఆరోగ్యం & ఆనందం",
    subtitle: "Dawn-Dispatched Across Visakhapatnam Doorsteps",
    location: "Pendurthi, MVP Colony, Seethammadhara, Gajuwaka, Madhurawada",
    quote: "From our fertile soil to your dining table within 3 to 6 hours.",
    image: "assets/natural_home_delivery.jpg",
    details: [
      { label: "Delivery Radius", value: "Same-Day across entire Visakhapatnam metropolitan area" },
      { label: "Packaging", value: "Plastic-free corrugated crates, jute sacks & unbleached paper" },
      { label: "Freshness Window", value: "Harvested at dawn, delivered to your kitchen before lunch" },
      { label: "Community", value: "Over 2,400 Visakhapatnam families thriving on pure nutrition" }
    ],
    interactivePrompt: "Customize your personalized farm crate and schedule your weekly organic harvest box."
  }
];

const SAMPLE_BATCH_REPORTS = {
  "VIZ-PND-OIL-428": {
    product: "Wood-Churned Groundnut Oil (1L)",
    farmer: "Appala Naidu (Farm ID: PND-09)",
    farmLocation: "Pendurthi Agro-Cluster, Visakhapatnam",
    harvestDate: "12 Oct 2026",
    pressDate: "14 Oct 2026",
    extractionMethod: "Traditional Vaagai Wood Gaani (Lakdi Ghani)",
    extractionTemp: "31.4°C (Safe limit < 40°C)",
    pesticideResidue: "0.00 ppm (120 agrochemical panel negative)",
    heavyMetals: "Lead < 0.01 ppm, Arsenic < 0.01 ppm (Compliant)",
    freeFattyAcids: "0.34% (Extra virgin grade)",
    peroxideValue: "1.2 meq/kg (Freshly pressed, zero rancidity)",
    vitaminE: "18.6 mg / 100g (Naturally preserved)"
  },
  "ARK-HNY-WLD-890": {
    product: "Araku Valley Raw Rock-Bee Honey (500g)",
    farmer: "Girijan Tribal Cooperative, Ananthagiri",
    farmLocation: "Eastern Ghats Reserve Forest, Araku Valley",
    harvestDate: "28 Sep 2026",
    pressDate: "Unheated / Cold Settled",
    extractionMethod: "Traditional Smoke-Free Comb Harvest",
    extractionTemp: "28.0°C (Never pasteurized)",
    pesticideResidue: "0.00 ppm (Wild forest flora, pure pristine canopy)",
    heavyMetals: "Nil / Zero Heavy Metal contamination",
    moistureContent: "18.2% (Natural thick viscosity)",
    pollenCount: "28,400 pollen grains/g (Active enzyme rich)",
    addedSugars: "0.00% (Zero C3/C4 corn syrup or rice syrup adulteration)"
  },
  "VIZ-MLT-FOX-711": {
    product: "Unpolished Foxtail Millet - Korralu (1kg)",
    farmer: "K. Satyanarayana (Farm ID: SBB-03)",
    farmLocation: "Sabbavaram Natural Farms, Visakhapatnam",
    harvestDate: "18 Aug 2026",
    pressDate: "Dehusked with Traditional Wooden Pestle / Rubber Roll",
    extractionMethod: "Zero Chemical Buffing",
    extractionTemp: "Ambient Room Temperature",
    pesticideResidue: "0.00 ppm (Zero organophosphates / Zero urea)",
    heavyMetals: "Non-detectable",
    glycemicIndex: "48 (Low GI, Diabetic Safe)",
    dietaryFiber: "8.1g / 100g (Full bran layer retained)",
    protein: "12.3g / 100g"
  }
};
